### ISSUE TITLE
What are the red lines on the schematic?

### ISSUE THREAD

**Issue by matprophet** [rpkish/Subduino-SSM#1]
The red lines on the left side of the schematic are not labeled.   Could you update the schematic to label what they are and what they are expected to be connected to?

**Comment by rpkish** [comment]
Hi, are you talking about the red lines that run to the left of the schematic? Those are 5v (from vcc on the arduino), it appears the schematic may have been inadvertently cropped.

**Comment by matprophet** [comment]
Thats correct, the red lines. I suspected they were 5V.  Something has gone wonky with the schematic, because was somehow able to see the full thing at some point.  Now its cropped.  Can you repair it and reload it?  There are some developers, including myself, that are interested in your project!

**Comment by rpkish** [comment]
I've updated the image. Thanks for letting me know about the issue. Cheers.
